
name: AIPU-Build-And-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  aipu-build-and-test:
    runs-on: aipu
    steps:
      - name: Checkout code (attempt 1)
        id: checkout1
        uses: actions/checkout@v4
        continue-on-error: true

      - name: Sleep before checkout2
        if: steps.checkout1.outcome == 'failure'
        run: |
          echo "First checkout attempt failed. Sleeping for 120 seconds before retry..."
          sleep 120

      - name: Checkout code (attempt 2)
        id: checkout2
        if: steps.checkout1.outcome == 'failure'
        uses: actions/checkout@v4
        continue-on-error: true

      - name: Sleep before final checkout
        if: steps.checkout1.outcome == 'failure' && steps.checkout2.outcome == 'failure'
        run: |
          echo "Second checkout attempt failed. Sleeping for 180 seconds before final retry..."
          sleep 180

      - name: Checkout code (final attempt)
        if: steps.checkout1.outcome == 'failure' && steps.checkout2.outcome == 'failure'
        uses: actions/checkout@v4

      - name: Verify checkout success
        if: success()
        run: echo "Checkout completed successfully"

      - name: FlagTree Build on AIPU
        shell: bash
        run: |
          source ~/env.sh
          source ~/env_setup.sh
          export FLAGTREE_BACKEND=aipu
          cd python
          python3.10 -m pip install . --no-build-isolation -v

      - name: FlagTree Test on AIPU
        shell: bash
        run: |
          source ~/env_setup.sh
          python3.10 third_party/aipu/python/test/test_01_vector_add.py
          python3.10 third_party/aipu/python/test/test_02_fused_softmax.py
